//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int Identifiant { get; set; }
        public int IdenfiantUtilisateur { get; set; }
        public System.DateTime DateSouscription { get; set; }
        public int Restant { get; set; }
        public Nullable<int> IdentifiantTypeAbonnement { get; set; }
    
        public virtual TypeAbonnement typeabonnement { get; set; }
        public virtual Utilisateur utilisateur { get; set; }
    }
}
