//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int Identifiant { get; set; }
        public int IdentifiantUtilisateur { get; set; }
        public System.DateTime DateSouscription { get; set; }
        public int Restant { get; set; }
        public Nullable<int> IdentifiantTypeAbonnement { get; set; }
    
        public virtual TypeAbonnement typeabonnement { get; set; }
        public virtual Utilisateur utilisateur { get; set; }
    }
}
