//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class competence
    {
        public int id { get; set; }
        public Nullable<int> utilisateur_id { get; set; }
        public Nullable<int> niveau_id { get; set; }
        public Nullable<int> typeCompetence_id { get; set; }
    
        public virtual typecompetence typecompetence { get; set; }
        public virtual niveau niveau { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
