//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competence
    {
        public int Identifiant { get; set; }
        public Nullable<int> IdentifiantUtilisateur { get; set; }
        public Nullable<int> IdentifiantNiveau { get; set; }
        public Nullable<int> IdentifiantTypeCompetence { get; set; }
    
        public virtual TypeCompetence typecompetence { get; set; }
        public virtual Niveau niveau { get; set; }
        public virtual Utilisateur utilisateur { get; set; }
    }
}
