//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competence
    {
        public int Identifiant { get; set; }
        public Nullable<int> IdentifiantUtilisateur { get; set; }
        public Nullable<int> IdentifiantNiveau { get; set; }
        public Nullable<int> IdentifiantTypeCompetence { get; set; }
    
        public virtual TypeCompetence typecompetence { get; set; }
        public virtual Niveau niveau { get; set; }
        public virtual Utilisateur utilisateur { get; set; }
    }
}
