//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int Identifiant { get; set; }
        public Nullable<int> IdentifiantUtilisateur { get; set; }
        public string Societe { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string Description { get; set; }
    
        public virtual Utilisateur utilisateur { get; set; }
    }
}
