//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metier
    {
        public Metier()
        {
            this.utilisateurs = new HashSet<Utilisateur>();
            this.offres = new HashSet<Offre>();
        }
    
        public int Identifiant { get; set; }
        public Nullable<int> IdentifiantDomaine { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Utilisateur> utilisateurs { get; set; }
        public virtual Domaine domaine { get; set; }
        public virtual ICollection<Offre> offres { get; set; }
    }
}
