//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metier
    {
        public Metier()
        {
            this.offres = new HashSet<Offre>();
            this.utilisateurs = new HashSet<Utilisateur>();
        }
    
        public int Identifiant { get; set; }
        public Nullable<int> IdentifiantDomaine { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Offre> offres { get; set; }
        public virtual ICollection<Utilisateur> utilisateurs { get; set; }
        public virtual Domaine domaine { get; set; }
    }
}
