//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multimedia
    {
        public int Identifiant { get; set; }
        public Nullable<int> IdentifiantUtilisateur { get; set; }
        public string Nom { get; set; }
        public string Url { get; set; }
        public Nullable<int> IdentifiantTypeMedia { get; set; }
    
        public virtual TypeMedia typemedia { get; set; }
        public virtual Utilisateur utilisateur { get; set; }
    }
}
