//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        public int Id { get; set; }
        public Nullable<int> Metier_id { get; set; }
        public string Description { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime Datefin { get; set; }
        public string Duree { get; set; }
        public Nullable<int> TypeContrat_id { get; set; }
        public string Intitule { get; set; }
        public bool IsActive { get; set; }
        public int Utilisateur_id { get; set; }
    
        public virtual Metier Metier { get; set; }
        public virtual TypeContrat TypeContrat { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
