//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeabonnement
    {
        public typeabonnement()
        {
            this.abonnements = new HashSet<abonnement>();
        }
    
        public int id { get; set; }
        public string libelle { get; set; }
        public int nbOffre { get; set; }
    
        public virtual ICollection<abonnement> abonnements { get; set; }
    }
}
