//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeContrat
    {
        public TypeContrat()
        {
            this.offres = new HashSet<Offre>();
        }
    
        public int Identifiant { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<Offre> offres { get; set; }
    }
}
