//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAbonnement
    {
        public TypeAbonnement()
        {
            this.abonnements = new HashSet<Abonnement>();
        }
    
        public int Identifiant { get; set; }
        public string Libelle { get; set; }
        public int NombreOffres { get; set; }
    
        public virtual ICollection<Abonnement> abonnements { get; set; }
    }
}
