//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public utilisateur()
        {
            this.abonnements = new HashSet<abonnement>();
            this.adresses = new HashSet<adresse>();
            this.competences = new HashSet<competence>();
            this.historiques = new HashSet<historique>();
            this.multimedias = new HashSet<multimedia>();
            this.domaines = new HashSet<domaine>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public System.DateTime dateNaissance { get; set; }
        public int typeUtilisateur_id { get; set; }
    
        public virtual ICollection<abonnement> abonnements { get; set; }
        public virtual ICollection<adresse> adresses { get; set; }
        public virtual ICollection<competence> competences { get; set; }
        public virtual ICollection<historique> historiques { get; set; }
        public virtual ICollection<multimedia> multimedias { get; set; }
        public virtual typeutilisateur typeutilisateur { get; set; }
        public virtual ICollection<domaine> domaines { get; set; }
    }
}
