//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.abonnements = new HashSet<Abonnement>();
            this.competences = new HashSet<Competence>();
            this.historiques = new HashSet<Historique>();
            this.multimedias = new HashSet<Multimedia>();
            this.metiers = new HashSet<Metier>();
            this.offres = new HashSet<Offre>();
        }
    
        public int Identifiant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Password { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public int IdentifiantTypeutilisateur { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> IdentifiantAdresse { get; set; }
        public string username { get; set; }
        public string username_canonical { get; set; }
        public string email_canonical { get; set; }
        public bool enabled { get; set; }
        public string salt { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public bool locked { get; set; }
        public bool expired { get; set; }
        public Nullable<System.DateTime> expires_at { get; set; }
        public string confirmation_token { get; set; }
        public Nullable<System.DateTime> password_requested_at { get; set; }
        public string roles { get; set; }
        public bool credentials_expired { get; set; }
        public Nullable<System.DateTime> credentials_expire_at { get; set; }
    
        public virtual ICollection<Abonnement> abonnements { get; set; }
        public virtual Adresse adresse { get; set; }
        public virtual ICollection<Competence> competences { get; set; }
        public virtual ICollection<Historique> historiques { get; set; }
        public virtual ICollection<Multimedia> multimedias { get; set; }
        public virtual TypeUtilisateur typeutilisateur { get; set; }
        public virtual ICollection<Metier> metiers { get; set; }
        public virtual ICollection<Offre> offres { get; set; }
    }
}
